#!/usr/bin/env bash
echo "Executing .git/hooks/pre-commit..."
VIOLATIONS=0

# Check backend
STANDARD="Drupal"
BIN="./vendor/bin"
DDEV="/usr/bin/ddev"

# Respect the configuration file included in the repo, if it exists.
if [ -f phpcs.xml ]; then
  STANDARD="phpcs.xml"
fi

echo
echo "Drupal Coder pre-commit hook – commit with the --no-verify option to skip the hook"
echo

# Check whether PHP_CodeSniffer can be found
if [ -f "$BIN/phpcs" ]; then

  # Run the check in ddev, if this is a ddev site.
  if [ -d .ddev ] && [ -x $DDEV ]; then
    PHPCS="$DDEV exec phpcs"
  else
    PHPCS="$BIN/phpcs"
  fi

else
  echo "Drupal Coder not found – is it installed?"
fi

# Run the sniffer
echo "Running Drupal Coder: ${PHPCS}"
echo
OUTPUT=(${PHPCS} --standard=${STANDARD} --filter=GitStaged --encoding=utf-8 -p .)
"${OUTPUT[@]}"
VIOLATIONS=$((VIOLATIONS + $?))

# Check frontend
echo "Running Frontend Lints."
echo
cd src/frontend || exit 1
npm run lint-staged
# Add frontend violations to the total
VIOLATIONS=$((VIOLATIONS + $?))

# One or more violations detected
if [ $VIOLATIONS != 0 ]
then
  echo "Please fix each violations detected."
  echo
  exit 1
fi

# Syntax OK
if [ $VIOLATIONS == 0 ]
then
  echo "No violations detected"
  echo
  exit 0
fi

git update-index --again


