import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docSidebar: [
    'index',
    {
      type: 'category',
      label: 'Development & Testing',
      collapsed: false,
      link: { type: 'doc', id: 'development/local/index' },
      items: [ { type: 'autogenerated', dirName: 'development/local' } ]
    },
    {
      type: 'category',
      label: 'Next.js front end',
      link: { type: 'doc', id: 'development/front-end/index' },
      items: [ { type: 'autogenerated', dirName: 'development/front-end' } ]
    },
    {
      type: 'category',
      label: 'Drupal back end',
      link: { type: 'doc', id: 'development/back-end/index' },
      items: [ { type: 'autogenerated', dirName: 'development/back-end' } ]
    }
    //{type: 'autogenerated', dirName: 'development'}
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
